version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
            - './.docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=my_db
            - MYSQL_PASSWORD=123456
        ports:
            - '8082:3306'
        restart: always
        container_name: mysql_my_blog

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: .docker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'
